spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false

---
spring:
  profiles: eureka1
server:
  port: 2001
  #eureka1 ��eureka2����ע��
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:2002/eureka/
---
spring:
  profiles: eureka2
server:
  port: 2002
  #eureka2��eureka1����ע��
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka/